# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epaper', '0004_auto_20161231_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_like', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de like')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_like', to='epaper.Noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=300),
        ),
    ]
